#include "string"

std::string sampleSource2 =
        "procedure First {"
        "      read x;"
        "      read z;\n"
        "      call Second; }\n"
        "\n"
        "procedure Second {\n"
        "        x = 0;\n"
        "        i = 5;\n"
        "        while (i!=0) {\n"
        "            x = x + 2*y;\n"
        "            call Third;\n"
        "            i = i - 1; }\n"
        "        if (x==1) then {\n"
        "            x = x+1; }\n"
        "        else {\n"
        "            z = 1; }\n"
        "        z = z + x + i;\n"
        "        y = z + 2;\n"
        "        x = x * y + z; }\n"
        "\n"
        "procedure Third {\n"
        "        z = 5;\n"
        "        v = z;\n"
        "        print v; }";
