name: CI for Cmake Project - Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: Build Project
        run: |
          cd Team17/Code17
          mkdir build
          cd build
          cmake -A Win32 ..
          cmake --build . --config Release
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release
          cd ../..

      - name: Run Unit Tests
        run: ./Team17/Code17/build/src/unit_testing/Release/unit_testing.exe

      - name: Run Integration Tests
        run: ./Team17/Code17/build/src/integration_testing/Release/integration_testing.exe

      - name: Run Autotester Tests
        run: |
          cd Team17/Tests17
          python3 regression_tester.py ../Code17/build/src/autotester/Release/autotester.exe
